THP.Web/Areas/Admin/Models/ServiceType/ServiceType.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace THP.Web.Areas.Admin.Models.ServiceType
{
    public class ServiceType
    {
        public int ServiceTypeId { get; set; }
        [Display(Name = "Name")]
        [Required(ErrorMessage = "Name is required")]
        [StringLength(50, ErrorMessage = "Maximum characters accepted is fifty(50)")]
        public string Name { get; set; }
        public string Description { get; set; }
        [Display(Name = "Date Created")]
        public DateTime DateCreated { get; set; }
        [Display(Name = "Created By")]
        public string CreatedBy { get; set; }
        [Display(Name = "Date Updated")]
        public DateTime DateUpdated { get; set; }
        [Display(Name = "Updated By")]
        public string UpdatedBy { get; set; }
    }
}

THP.Web/Areas/Admin/Models/ServiceType/ServiceTypeViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace THP.Web.Areas.Admin.Models.ServiceType
{
    public class ServiceTypeViewModel
    {
        [Display(Name = "Name")]
        public string Name { get; set; }

        public List<ServiceType> ServiceTypes { get; set; }
    }
}

THP.Web/Areas/Admin/Controllers/ServiceTypeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using THP.Web.Areas.Admin.Models.ServiceType;
using THP.Web.Models.Interface.DAL;
using THP.Web.Models.Security.Authorizations;

namespace THP.Web.Areas.Admin.Controllers
{
    public class ServiceTypeController : Controller
    {
        #region Fields

        private readonly IUnitOfWork _unitOfWork;

        #endregion

        #region Ctor

        public ServiceTypeController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        #endregion

        #region Methods

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Index()
        {
            ServiceTypeViewModel model = new ServiceTypeViewModel();
            model.ServiceTypes = _unitOfWork.ServiceType.GetServiceType(isDeleted: false).ToList();
            return View(model);
        }


        [CustomAuthorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Index(ServiceTypeViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.ServiceTypes = _unitOfWork.ServiceType
                        .GetServiceType(name: model.Name, isDeleted: false)
                        .ToList();
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

            return View(model);
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Add()
        {
            return View(new ServiceType());
        }

        [CustomAuthorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Add(ServiceType model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _unitOfWork.ServiceType.AddServiceType(model);
                    _unitOfWork.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

            return RedirectToAction("Edit", routeValues: new { @id = model.ServiceTypeId });
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue || id.Value == 0)
                return RedirectToAction("Index");

            var model = _unitOfWork.ServiceType.GetServiceType(id.Value);

            return View(model);
        }

        [CustomAuthorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(ServiceType model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _unitOfWork.ServiceType.UpdateServiceType(model);
                    _unitOfWork.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

            return RedirectToAction("Edit", routeValues: new { id = model.ServiceTypeId });
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (!id.HasValue || id.Value == 0)
                return RedirectToAction("Index");

            var model = _unitOfWork.ServiceType.Get(id.Value);
            model.Deleted = true;

            _unitOfWork.ServiceType.Update(model);
            _unitOfWork.SaveChanges();

            return RedirectToAction("Index");

        }
        #endregion
    }
}

THP.Web/Areas/Admin/Views/ServiceType/Add.cshtml
@model THP.Web.Areas.Admin.Models.ServiceType.ServiceType
@{
    ViewBag.Title = "Add";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Service Types
        <small>Different types of services you offer on your website</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index")"><i class="fa fa-files-o"></i> Catalog</a></li>
        <li><a href="@Url.Action("Index")">Service Type</a></li>
        <li class="active">Add</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Service Type Information</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                                title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                @using (Html.BeginForm("Add", "ServiceType", FormMethod.Post))
                {
                    <div class="box-body">
                        <div class="row">
                            @Html.HiddenFor(m => m.ServiceTypeId)
                            <div class="col-lg-12 col-md-12">
                                <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Name)
                                        @Html.TextBoxFor(m => m.Name, "", htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Name, "", htmlAttributes: new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Description)
                                        @Html.TextAreaFor(m => m.Description, rows: 5, columns: 5, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Description, "", htmlAttributes: new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <input type="submit" class="btn btn-primary" value="Save" />
                    </div>
                    <!-- /.box-footer-->
                }
            </div>
        </div>
    </div>
</section>

THP.Web/Areas/Admin/Views/ServiceType/Edit.cshtml
@model THP.Web.Areas.Admin.Models.ServiceType.ServiceType
@{
    ViewBag.Title = "Edit";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Service Types
        <small>Different types of services you offer on your website</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index")"><i class="fa fa-files-o"></i> Catalog</a></li>
        <li><a href="@Url.Action("Index")">Service Type</a></li>
        <li class="active">@Model.ServiceTypeId</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Service Type Information</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                                title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                @using (Html.BeginForm("Edit", "ServiceType", FormMethod.Post))
                {
                    <div class="box-body">
                        <div class="row">
                            @Html.HiddenFor(m => m.ServiceTypeId)
                            <div class="col-lg-12 col-md-12">
                                <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Name)
                                        @Html.TextBoxFor(m => m.Name, "", htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Name, "", htmlAttributes: new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Description)
                                        @Html.TextAreaFor(m => m.Description, rows: 5, columns: 5, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Description, "", htmlAttributes: new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <input type="submit" class="btn btn-primary" value="Save" />
                    </div>
                    <!-- /.box-footer-->
                }
            </div>
        </div>
    </div>
</section>

THP.Web/Areas/Admin/Views/ServiceType/Index.cshtml
@model THP.Web.Areas.Admin.Models.ServiceType.ServiceTypeViewModel


@{
    ViewBag.Title = "Service Types";
}

@section css{

    <!-- DataTables -->
    <link rel="stylesheet" href="~/Content/Admin/datatables.net-bs/css/dataTables.bootstrap.min.css">
}

<!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Service Types
            <small>Different types of services you offer on your website</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-files-o"></i> Catalog</a></li>
            <li class="active">Service Types</li>
        </ol>
    </section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Search Filter</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                                title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    Start creating your amazing application!
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    Footer
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->
            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Record</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                                title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="pull-left">
                        <a class="btn bg-blue" href="@Url.Action("Add")">
                            <i class="fa fa-plus-square"></i>
                            Add new
                        </a>
                    </div>
                    <table id="main-table" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Created</th>
                                <th>Updated</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var data in Model.ServiceTypes)
                            {
                                <tr>
                                    <td>@data.Name</td>
                                    <td>
                                        <span>Date Created: @data.DateCreated</span>
                                        <br />
                                        <span>Created By: @data.CreatedBy</span>
                                    </td>
                                    <td>
                                        <span>Date Updated: @data.DateUpdated</span>
                                        <br />
                                        <span>Updated By: @data.UpdatedBy</span>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit","ServiceType", routeValues: new { @id = data.ServiceTypeId })" class="btn btn-default btn-sm">
                                            <i class="fa fa-eye"></i> Edit
                                        </a>
                                        <a href="@Url.Action("Delete","ServiceType", routeValues: new { @id = data.ServiceTypeId })"
                                           onclick="return confirm('You are about to delete this record, are you sure you want to continue?')"
                                           class="btn btn-default btn-sm">
                                            <i class="fa fa-trash-o"></i> Delete
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
<!-- /.content -->

@section scripts{

    <!-- DataTables -->
    <script src="~/Content/Admin/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/Admin/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
      $(function () {
        $('#main-table').DataTable({
          'paging'      : true,
          'lengthChange': false,
          'searching'   : true,
          'ordering'    : true,
          'info'        : true,
          'autoWidth'   : false
        })
      })
    </script>
}