THP.Web/Models/DAL/Data/Order/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace THP.Web.Models.DAL.Data.Order
{
    public class OrderViewModel
    {
        public OrderViewModel()
        {
            Ratings = new List<SelectListItem>();
            Ratings.Add(new SelectListItem
            {
                Text = 1.ToString(),
                Value = 1.ToString()
            });
            Ratings.Add(new SelectListItem
            {
                Text = 2.ToString(),
                Value = 2.ToString()
            });
            Ratings.Add(new SelectListItem
            {
                Text = 3.ToString(),
                Value = 3.ToString()
            });
            Ratings.Add(new SelectListItem
            {
                Text = 4.ToString(),
                Value = 4.ToString()
            });
            Ratings.Add(new SelectListItem
            {
                Text = 5.ToString(),
                Value = 5.ToString()
            });
        }

        [Display(Name = "Booking Id")]
        public int BookingId { get; set; }
        [Display(Name = "Booking No")]
        public string BookingNo { get; set; }
        [Display(Name = "Driver Name")]
        public string DriverName { get; set; }
        [Display(Name = "Customer Name")]
        public string CustomerName { get; set; }
        [Display(Name = "Start Date Schedule")]
        public DateTime StartDateSchedule { get; set; }
        [Display(Name = "End Date Schedule")]
        public DateTime EndDateSchedule { get; set; }
        [Display(Name = "Pick-up Point")]
        public string PickupPoint { get; set; }
        [Display(Name = "Destinaation Point")]
        public string DestinationPoint { get; set; }
        [Display(Name = "Total Price")]
        public decimal TotalPrice { get; set; }
        [Display(Name = "Currency")]
        public string Currency { get; set; }
        [Display(Name = "Payment Type")]
        public string PaymentType { get; set; }
        [Display(Name = "Booking Status")]
        public string Status { get; set; }
        [Display(Name = "Seater")]
        public int Seater { get; set; }

        public int CustomerID { get; set; }
        public int BookingReviewID { get; set; }

        [Display(Name = "Review Message")]
        public string Message { get; set; }
        [Display(Name = "Ratings")]
        public int Rating { get; set; }
        public List<SelectListItem> Ratings { get; set; }
    }
}

THP.Web/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using THP.Web.Models;
using THP.Web.Models.DAL.Data.Booking;
using THP.Web.Models.Entities.Data;
using THP.Web.Models.Interface.Configuration;
using THP.Web.Models.Interface.DAL;
using THP.Web.Models.Security.Authorizations;
using Braintree;

namespace THP.Web.Controllers
{
    public class BookingController : Controller
    {
        #region Properties

        public readonly IUnitOfWork _unitOfWork;
        public readonly IBraintreeConfiguration _braintreeConfiguration;

        #endregion

        #region Ctor
        public BookingController(IUnitOfWork unitOfWork, IBraintreeConfiguration braintreeConfiguration)
        {
            this._unitOfWork = unitOfWork;
            this._braintreeConfiguration = braintreeConfiguration;
        }
        #endregion

        #region Utilities

        public List<string> GetDatesUnavailable(List<Booking> bookings)
        {
            var reservedSchedules = _unitOfWork.Booking.GetReservedSchedules(bookings);

            // Get all drivers
            var userIds = _unitOfWork.User.GetDrivers(isDeleted: false)
                .Select(m => m.ID);

            var unavailableDates = new List<string>();

            foreach (var reservedSchedule in  reservedSchedules)
            {
                // Check record if all the drivers have been booked on that day.
                var driverAvailable = userIds.Where(m => !reservedSchedule.DriverIds.Contains(m)).Count();

                // if no drivers are available store them in the list
                if (driverAvailable == 0)
                    unavailableDates.Add(reservedSchedule.ReservedDate.ToString("MM/dd/yyyy"));
            }
            
            return unavailableDates.OrderBy(m => m).ToList();
        }

        [HttpPost]
        public JsonResult GetTotalPrice(int pickUpPointID, int destinationPointID, DateTime? startDate = null, DateTime? endDate = null)
        {

            var travelRate = _unitOfWork.TravelRate
                .FirstOrDefault(m => m.PickupPointID == pickUpPointID & m.DestinationPointID == destinationPointID);

            //var datetest = DateTime.Now;
            //var start = DateTime.ParseExact(startDate, "MM/dd/yyyy hh:mm", null);
            //var end = DateTime.ParseExact(endDate, "MM/dd/yyyy hh:mm", null);

            var price = _unitOfWork.Booking.ComputeTotalPrice(travelRate.FixedPrice, startDate, endDate);
            return Json(price.ToString());
        }

        [HttpPost]
        public JsonResult GetDisabledDates()
        {
            var dateToday = DateTime.UtcNow.ToLocalTime().Date;
            var bookings = _unitOfWork.Booking
                .Find(m => m.StartDateScheduled >= dateToday)
                .ToList();

            var datesUnavailable = GetDatesUnavailable(bookings).ToArray();
            return Json(datesUnavailable, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CompleteBooking(int bookingId)
        {
            var booking = _unitOfWork.Booking.Get(bookingId);

            // Check if deleted 
            if (booking.Deleted)
            {
                return Json(new { Message = "Booking does not exist", IsSuccess = false });
            }

            // Check if date is already done
            var dateToday = DateTime.UtcNow;
            if (booking.EndDateScheduled > dateToday)
            {
                return Json(new { Message = "Schedule of booking is not yet finished", IsSuccess = false });
            }

            booking.Status = Constant.BOOKING_STATUS_COMPLETE;
            booking.DateCompleted = DateTime.UtcNow;
            booking.DateUpdated = DateTime.UtcNow;
            booking.UpdatedBy = AccountConstant.UserID;

            var userCar = _unitOfWork.UserCar
                .Find(m => m.UserID == AccountConstant.UserID)
                .LastOrDefault();

            if (userCar != null)
            {
                var currentTotalKm = userCar.TotalKilometer.HasValue ? userCar.TotalKilometer.Value : 0;
                userCar.TotalKilometer = currentTotalKm + booking.Kilometer;

                _unitOfWork.UserCar.Update(userCar);
            }

            _unitOfWork.Booking.Update(booking);

            // Create a notifcation for customer
            var notification = new Notification
            {
                UserID = booking.UserID,
                Message = $"{booking.BookingNo} - is now completed",
                IsClicked = true,
                CreatedBy = booking.UserID,
                DateCreated = DateTime.UtcNow,
                UpdatedBy = booking.UserID,
                DateUpdated = DateTime.UtcNow
            };

            _unitOfWork.Notification.Add(notification);

            notification = new Notification
            {
                UserID = booking.DriverUserID,
                Message = $"{booking.BookingNo} - is now completed",
                IsClicked = false,
                CreatedBy = booking.DriverUserID,
                DateCreated = DateTime.UtcNow,
                UpdatedBy = booking.DriverUserID,
                DateUpdated = DateTime.UtcNow
            };

            _unitOfWork.SaveChanges();
            return Json(new { Message = "Booking Complete!", IsSuccess = true });
        }

        [HttpPost]
        public JsonResult OnGoingBooking(int bookingId)
        {
            var booking = _unitOfWork.Booking.Get(bookingId);

            // Check if deleted 
            if (booking.Deleted)
            {
                return Json(new { Message = "Booking does not exist" });
            }

            // Check if date is already done
            var dateToday = DateTime.UtcNow;
            if (booking.EndDateScheduled > dateToday)
            {
                return Json(new { Message = "Schedule of booking is not yet starting" });
            }

            booking.Status = Constant.BOOKING_STATUS_ONGOING;
            booking.DateUpdated = DateTime.UtcNow;
            booking.UpdatedBy = AccountConstant.UserID;
            booking.DateCompleted = DateTime.UtcNow;

            _unitOfWork.Booking.Update(booking);

            return Json(new { Message = "Booking is now On Going!" });
        }

        [HttpPost]
        public JsonResult CancelBooking(int bookingId)
        {
            var booking = _unitOfWork.Booking.Get(bookingId);

            // Check if deleted 
            if (booking.Deleted)
            {
                return Json(new { Message = "Booking does not exist", IsSuccess = false });
            }

            // Check if date is already done
            //var dateToday = DateTime.UtcNow;
            //if (booking.EndDateScheduled > dateToday)
            //{
            //    return Json(new { Message = "Schedule of booking is not yet finished", IsSuccess = false });
            //}

            // Braintree gateway configuration
            var gateway = _braintreeConfiguration.GetGateway();
            var transaction = gateway.Transaction.Refund(booking.TransactionID, booking.TotalPrice);

            if (transaction.IsSuccess())
            {
                booking.Status = Constant.BOOKING_STATUS_CANCELLED;
                booking.DateUpdated = DateTime.UtcNow;
                booking.UpdatedBy = AccountConstant.UserID;

                _unitOfWork.Booking.Update(booking);

                // Create a notifcation for customer
                var notification = new Notification
                {
                    UserID = booking.UserID,
                    Message = $"{booking.BookingNo} - has been cancelled",
                    IsClicked = true,
                    CreatedBy = booking.UserID,
                    DateCreated = DateTime.UtcNow,
                    UpdatedBy = booking.UserID,
                    DateUpdated = DateTime.UtcNow
                };

                _unitOfWork.Notification.Add(notification);

                notification = new Notification
                {
                    UserID = booking.DriverUserID,
                    Message = $"{booking.BookingNo} - has been cancelled",
                    IsClicked = false,
                    CreatedBy = booking.DriverUserID,
                    DateCreated = DateTime.UtcNow,
                    UpdatedBy = booking.DriverUserID,
                    DateUpdated = DateTime.UtcNow
                };

                _unitOfWork.Notification.Add(notification);

                _unitOfWork.SaveChanges();

                return Json(new { Message = "Booking Cancelled!", IsSuccess = true });
            }
            else
            {

                return Json(new { Message = transaction.Message, IsSuccess = false });
            }
        }

        [HttpPost]
        public JsonResult BookingConfig()
        {
            var retval = false;

            if (AccountConstant.UserID != 0)
            {
                var booking = _unitOfWork.Booking.Find(m => m.UserID == AccountConstant.UserID)
                    .LastOrDefault();

                if (booking != null 
                    && (booking.Status != Constant.BOOKING_STATUS_COMPLETE 
                    && booking.Status != Constant.BOOKING_STATUS_CANCELLED)
                    )
                    retval = true;
            }

            return Json(new { hasBooking = retval });
        }

        #endregion

        #region Methods

        [CustomAuthorize]
        // GET: Booking
        public ActionResult Index()
        {
            BookingViewModel model = new BookingViewModel();

            try
            {
                //var locations = _unitOfWork.Location.Find(m => m.ParentLocationID != 0);

                _unitOfWork.Location
                    .Find(m => m.ID == 1)
                    .ToList()
                    .ForEach(m => model.lst_PickUpPointID.Add(
                        new SelectListItem
                        {

THP.Web/Controllers/OrderController.cs
using System;
using System.Web.Mvc;
using THP.Web.Models;
using THP.Web.Models.DAL.Data.Order;
using THP.Web.Models.Entities.Data;
using THP.Web.Models.Interface.DAL;
using THP.Web.Models.Security.Authorizations;

namespace THP.Web.Controllers
{
    public class OrderController : Controller
    {
        #region Fields

        private readonly IUnitOfWork _unitOfWork;

        #endregion

        #region Ctor

        public OrderController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        #endregion


        #region Methods

        [CustomAuthorize]
        // GET: Order
        public ActionResult Details(int? id)
        {
            try
            {
                var model = _unitOfWork.Booking.GetBooking(id.Value);
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Details", new { id = id });
            }
        }

        [CustomAuthorize]
        [HttpPost]
        public ActionResult Details(OrderViewModel model)
        {
            try
            {
                var bookingReview = new BookingReview
                {
                    UserID = AccountConstant.UserID,
                    BookingID = model.BookingId,
                    Message = model.Message,
                    Rating = model.Rating,
                    DateCreated = DateTime.UtcNow,
                    CreatedBy = AccountConstant.UserID,
                    DateUpdated = DateTime.UtcNow,
                    UpdatedBy = AccountConstant.UserID,
                    Deleted = false
                };

                _unitOfWork.BookingReview.Add(bookingReview);
                _unitOfWork.SaveChanges();
            }
            catch (Exception ex)
            {
                // Log Error Message
                TempData["ErrorMessage"] = ex.Message;
            }

            return RedirectToAction("Details", new { id = model.BookingId });
        }
        #endregion

    }
}

THP.Web/Views/Order/Details.cshtml
@model THP.Web.Models.DAL.Data.Order.OrderViewModel
@using THP.Web.Models
@using THP.Web.Models.DAL.Data.Enum
@{
    ViewBag.Title = "Booking Detail";
}

<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
    <div class="container">
        <div class="row">
            <!-- Page Title Start -->
            <div class="col-lg-12">
                <div class="section-title  text-center">
                    <h2>Booking</h2>
                    <span class="title-line"><i class="fa fa-car"></i></span>
                    <p>
                        View more details of your booking to see the information you have provided to the system
                    </p>
                </div>
            </div>
            <!-- Page Title End -->
        </div>
    </div>
</section>
<!--== Page Title Area End ==-->
<!--== Detail Area Start ==-->
<div class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 m-auto">
                <div class="profile-form">
                    <div class="row">
                        <!-- Section Title Start -->
                        <div class="col-lg-12">
                            <div class="section-title  text-center">
                                <h2>Booking Details</h2>
                                <span class="title-line"><i class="fa fa-car"></i></span>
                                <p>more information</p>
                            </div>
                        </div>
                        <!-- Section Title End -->
                    </div>
                    <!--== Booking Area Start ==-->
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="text-input">
                                @Html.LabelFor(m => m.BookingNo)
                                @Html.TextBoxFor(m => m.BookingNo, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <div class="text-input">
                                @Html.LabelFor(m => m.DriverName)
                                @Html.TextBoxFor(m => m.DriverName, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="text-input">
                                @Html.LabelFor(m => m.StartDateSchedule)
                                @Html.TextBoxFor(m => m.StartDateSchedule, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="text-input">
                                @Html.LabelFor(m => m.EndDateSchedule)
                                @Html.TextBoxFor(m => m.EndDateSchedule, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="text-input">
                                @Html.LabelFor(m => m.PickupPoint)
                                @Html.TextBoxFor(m => m.PickupPoint, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="text-input">
                                @Html.LabelFor(m => m.DestinationPoint)
                                @Html.TextBoxFor(m => m.DestinationPoint, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="text-input">
                                @Html.LabelFor(m => m.Seater)
                                @Html.TextBoxFor(m => m.Seater, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="text-input">
                                @Html.LabelFor(m => m.Status)
                                @Html.TextBoxFor(m => m.Status, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-lg-4 col-md-4">
                            <div class="text-input">
                                @Html.LabelFor(m => m.Currency)
                                @Html.TextBoxFor(m => m.Currency, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="text-input">
                                @Html.LabelFor(m => m.TotalPrice)
                                @Html.TextBoxFor(m => m.TotalPrice, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="text-input">
                                @Html.LabelFor(m => m.PaymentType)
                                @Html.TextBoxFor(m => m.PaymentType, "", htmlAttributes: new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <div class="input-submit">
                                @if (Model.Status != Constant.BOOKING_STATUS_COMPLETE || Model.Status != Constant.BOOKING_STATUS_CANCELLED)
                                {
                                    if (HttpContext.Current.Session["roleID"] != null && HttpContext.Current.Session["roleID"].ToString() != Convert.ToString((int)RoleType.Customer))
                                    {
                                        <button class="pull-right btn btn-success" onclick="CompleteBooking(@Model.BookingId)" title="Complete Booking">Complete</button>
                                    }

                                    if (HttpContext.Current.Session["roleID"] != null && HttpContext.Current.Session["roleID"].ToString() != Convert.ToString((int)RoleType.Driver))
                                    {
                                        <button class="pull-right btn btn-danger" onclick="CancelBooking(@Model.BookingId)" title="Cancel Booking">Cancel</button>
                                    }
                                }
                                <!--<a href="@Url.Action("AccountProfile", "Account")" class="pull-right btn btn-warning">Back</a>-->
                            </div>
                        </div>
                    </div>
                    <!--== Booking Area End ==-->
                </div>
            </div>
        </div>
    </div>
</div>
<!--== Detail Area End ==-->
@if (Model.Status == Constant.BOOKING_STATUS_COMPLETE && Model.CustomerID == AccountConstant.UserID)
{
    <!--== Booking Review Area Start ==-->
    <section class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 m-auto">
                    <div class="profile-form">
                        <div class="row">
                            <!-- Section Title Start -->
                            <div class="col-lg-12">
                                <div class="section-title  text-center">
                                    <h2>Booking Review</h2>
                                    <span class="title-line"><i class="fa fa-car"></i></span>
                                    <p>How was your experience on our service?</p>
                                </div>
                            </div>
                            <!-- Section Title End -->
                        </div>
                        @if (Model.BookingReviewID == 0)
                        {
                            using (Html.BeginForm("Details", "Order", FormMethod.Post))
                            {
                                <!--== Booking Review Area Start ==-->
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(m => m.BookingId)
                                <div class="row">
                                    <div class="col-lg-12 col-md-12">
                                        <div class="text-input">
                                            @Html.LabelFor(m => m.Rating)
                                            @Html.DropDownListFor(m => m.Rating, Model.Ratings, "-- Select Rating --", htmlAttributes: new { @class = "custom-select custom-select-style" })
                                        </div>
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-lg-12 col-md-12">
                                        <div class="text-input">
                                            @Html.LabelFor(m => m.Message)
                                            @Html.TextAreaFor(m => m.Message, htmlAttributes: new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-lg-12 col-md-12">
                                        <div class="input-submit">
                                            <button type="submit" class="pull-right">Submit Review</button>
                                        </div>
                                    </div>
                                </div>
                                <!--== Booking Review Area End ==-->
                            }
                        }
                        else
                        {
                            <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <div class="text-input">
                                        @Html.LabelFor(m => m.Rating)
                                        @Html.DropDownListFor(m => m.Rating, Model.Ratings, "-- Select Rating --", htmlAttributes: new { @class = "custom-select custom-select-style", @readonly = "true" })
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <div class="text-input">
                                        @Html.LabelFor(m => m.Message)
                                        @Html.TextAreaFor(m => m.Message, htmlAttributes: new { @class = "form-control", @readonly = "true" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--== Booking Review Area End ==-->
}

@section scripts
{
    <script>
        function CompleteBooking(id) {

            var confirmation = confirm('Are you sure you want to coninue?');

            if (confirmation == true) {
                $.ajax({
                    url: '@Url.Action("CompleteBooking", "Booking" )',
                    contentType: 'application/json',
                    type: 'POST',
                    data: JSON.stringify({
                        bookingId: id
                    }),
                    success: function (data) {

                        alert(data.Message);
                    }
                });
            }
        }

        function CancelBooking(id) {

            var confirmation = confirm('Are you sure you want to coninue?');

            if (confirmation == true) {
                $.ajax({
                    url: '@Url.Action("CancelBooking", "Booking" )',
                    contentType: 'application/json',
                    type: 'POST',
                    data: JSON.stringify({
                        bookingId: id
                    }),
                    success: function (data) {

                        alert(data.Message);
                    }
                });
            }
        }
    </script>
}