THP.Web/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using THP.Web.Models;
using THP.Web.Models.DAL.Data.Booking;
using THP.Web.Models.Entities.Data;
using THP.Web.Models.Interface.Configuration;
using THP.Web.Models.Interface.DAL;
using THP.Web.Models.Security.Authorizations;
using Braintree;

namespace THP.Web.Controllers
{
    public class BookingController : Controller
    {
        #region Properties

        public readonly IUnitOfWork _unitOfWork;
        public readonly IBraintreeConfiguration _braintreeConfiguration;

        #endregion

        #region Ctor
        public BookingController(IUnitOfWork unitOfWork, IBraintreeConfiguration braintreeConfiguration)
        {
            this._unitOfWork = unitOfWork;
            this._braintreeConfiguration = braintreeConfiguration;
        }
        #endregion

        #region Utilities

        public List<string> GetDatesUnavailable(List<Booking> bookings)
        {
            var reservedSchedules = _unitOfWork.Booking.GetReservedSchedules(bookings);

            // Get all drivers
            var userIds = _unitOfWork.User.GetDrivers(isDeleted: false)
                .Select(m => m.ID);

            var unavailableDates = new List<string>();

            foreach (var reservedSchedule in  reservedSchedules)
            {
                // Check record if all the drivers have been booked on that day.
                var driverAvailable = userIds.Where(m => !reservedSchedule.DriverIds.Contains(m)).Count();

                // if no drivers are available store them in the list
                if (driverAvailable == 0)
                    unavailableDates.Add(reservedSchedule.ReservedDate.ToString("MM/dd/yyyy"));
            }
            
            return unavailableDates.OrderBy(m => m).ToList();
        }

        [HttpPost]
        public JsonResult GetTotalPrice(int pickUpPointID, int destinationPointID, DateTime? startDate = null, DateTime? endDate = null)
        {

            var travelRate = _unitOfWork.TravelRate
                .FirstOrDefault(m => m.PickupPointID == pickUpPointID & m.DestinationPointID == destinationPointID);

            //var datetest = DateTime.Now;
            //var start = DateTime.ParseExact(startDate, "MM/dd/yyyy hh:mm", null);
            //var end = DateTime.ParseExact(endDate, "MM/dd/yyyy hh:mm", null);

            var price = _unitOfWork.Booking.ComputeTotalPrice(travelRate.FixedPrice, startDate, endDate);
            return Json(price.ToString());
        }

        [HttpPost]
        public JsonResult GetDisabledDates()
        {
            var dateToday = DateTime.UtcNow.ToLocalTime().Date;
            var bookings = _unitOfWork.Booking
                .Find(m => m.StartDateScheduled >= dateToday)
                .ToList();

            var datesUnavailable = GetDatesUnavailable(bookings).ToArray();
            return Json(datesUnavailable, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CompleteBooking(int bookingId)
        {
            var booking = _unitOfWork.Booking.Get(bookingId);

            // Check if deleted 
            if (booking.Deleted)
            {
                return Json(new { Message = "Booking does not exist", IsSuccess = false });
            }

            // Check if date is already done
            var dateToday = DateTime.UtcNow;
            if (booking.EndDateScheduled > dateToday)
            {
                return Json(new { Message = "Schedule of booking is not yet finished", IsSuccess = false });
            }

            booking.Status = Constant.BOOKING_STATUS_COMPLETE;
            booking.DateCompleted = DateTime.UtcNow;
            booking.DateUpdated = DateTime.UtcNow;
            booking.UpdatedBy = AccountConstant.UserID;

            var userCar = _unitOfWork.UserCar
                .Find(m => m.UserID == AccountConstant.UserID)
                .LastOrDefault();

            if (userCar != null)
            {
                var currentTotalKm = userCar.TotalKilometer.HasValue ? userCar.TotalKilometer.Value : 0;
                userCar.TotalKilometer = currentTotalKm + booking.Kilometer;

                _unitOfWork.UserCar.Update(userCar);
            }

            _unitOfWork.Booking.Update(booking);

            // Create a notifcation for customer
            var notification = new Notification
            {
                UserID = booking.UserID,
                Message = $"{booking.BookingNo} - is now completed",
                IsClicked = true,
                CreatedBy = booking.UserID,
                DateCreated = DateTime.UtcNow,
                UpdatedBy = booking.UserID,
                DateUpdated = DateTime.UtcNow
            };

            _unitOfWork.Notification.Add(notification);

            notification = new Notification
            {
                UserID = booking.DriverUserID,
                Message = $"{booking.BookingNo} - is now completed",
                IsClicked = false,
                CreatedBy = booking.DriverUserID,
                DateCreated = DateTime.UtcNow,
                UpdatedBy = booking.DriverUserID,
                DateUpdated = DateTime.UtcNow
            };

            _unitOfWork.SaveChanges();
            return Json(new { Message = "Booking Complete!", IsSuccess = true });
        }

        [HttpPost]
        public JsonResult OnGoingBooking(int bookingId)
        {
            var booking = _unitOfWork.Booking.Get(bookingId);

            // Check if deleted 
            if (booking.Deleted)
            {
                return Json(new { Message = "Booking does not exist" });
            }

            // Check if date is already done
            var dateToday = DateTime.UtcNow;
            if (booking.EndDateScheduled > dateToday)
            {
                return Json(new { Message = "Schedule of booking is not yet starting" });
            }

            booking.Status = Constant.BOOKING_STATUS_ONGOING;
            booking.DateUpdated = DateTime.UtcNow;
            booking.UpdatedBy = AccountConstant.UserID;
            booking.DateCompleted = DateTime.UtcNow;

            _unitOfWork.Booking.Update(booking);

            return Json(new { Message = "Booking is now On Going!" });
        }

        [HttpPost]
        public JsonResult CancelBooking(int bookingId)
        {
            var booking = _unitOfWork.Booking.Get(bookingId);

            // Check if deleted 
            if (booking.Deleted)
            {
                return Json(new { Message = "Booking does not exist", IsSuccess = false });
            }

            // Check if date is already done
            //var dateToday = DateTime.UtcNow;
            //if (booking.EndDateScheduled > dateToday)
            //{
            //    return Json(new { Message = "Schedule of booking is not yet finished", IsSuccess = false });
            //}

            // Braintree gateway configuration
            var gateway = _braintreeConfiguration.GetGateway();
            var transaction = gateway.Transaction.Refund(booking.TransactionID, booking.TotalPrice);

            if (transaction.IsSuccess())
            {
                booking.Status = Constant.BOOKING_STATUS_CANCELLED;
                booking.DateUpdated = DateTime.UtcNow;
                booking.UpdatedBy = AccountConstant.UserID;

                _unitOfWork.Booking.Update(booking);

                // Create a notifcation for customer
                var notification = new Notification
                {
                    UserID = booking.UserID,
                    Message = $"{booking.BookingNo} - has been cancelled",
                    IsClicked = true,
                    CreatedBy = booking.UserID,
                    DateCreated = DateTime.UtcNow,
                    UpdatedBy = booking.UserID,
                    DateUpdated = DateTime.UtcNow
                };

                _unitOfWork.Notification.Add(notification);

                notification = new Notification
                {
                    UserID = booking.DriverUserID,
                    Message = $"{booking.BookingNo} - has been cancelled",
                    IsClicked = false,
                    CreatedBy = booking.DriverUserID,
                    DateCreated = DateTime.UtcNow,
                    UpdatedBy = booking.DriverUserID,
                    DateUpdated = DateTime.UtcNow
                };

                _unitOfWork.Notification.Add(notification);

                _unitOfWork.SaveChanges();

                return Json(new { Message = "Booking Cancelled!", IsSuccess = true });
            }
            else
            {

                return Json(new { Message = transaction.Message, IsSuccess = false });
            }
        }

        [HttpPost]
        public JsonResult BookingConfig()
        {
            var retval = false;

            if (AccountConstant.UserID != 0)
            {
                var booking = _unitOfWork.Booking.Find(m => m.UserID == AccountConstant.UserID)
                    .LastOrDefault();

                if (booking != null 
                    && (booking.Status != Constant.BOOKING_STATUS_COMPLETE 
                    && booking.Status != Constant.BOOKING_STATUS_CANCELLED)
                    )
                    retval = true;
            }

            return Json(new { hasBooking = retval });
        }

        #endregion

        #region Methods

        [CustomAuthorize]
        // GET: Booking
        public ActionResult Index()
        {
            BookingViewModel model = new BookingViewModel();

            try
            {
                //var locations = _unitOfWork.Location.Find(m => m.ParentLocationID != 0);

                _unitOfWork.Location
                    .Find(m => m.ID == 1)
                    .ToList()
                    .ForEach(m => model.lst_PickUpPointID.Add(
                        new SelectListItem
                        {

THP.Web/Controllers/TrackingController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using THP.Web.Models;
using THP.Web.Models.DAL.Data.Tracking;
using THP.Web.Models.Interface.DAL;
using THP.Web.Models.Security.Authorizations;

namespace THP.Web.Controllers
{
    public class TrackingController : Controller
    {
        #region Fields

        public readonly IUnitOfWork _unitOfWork;

        #endregion

        #region Ctor

        public TrackingController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        #endregion

        #region Methods

        [CustomAuthorize]
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetMeetupLocation()
        {
            var userID = AccountConstant.UserID;
            var date = DateTime.Now;

            var booking = _unitOfWork.Booking
                .Find(m => m.UserID == userID && m.StartDateScheduled <= date && m.EndDateScheduled >= date)
                .OrderByDescending(m => m.ID)
                .FirstOrDefault();

            return Json(new { address = booking.TravelRate.PickupPoint.Name });
        }

        public JsonResult GetDriverLocation()
        {
            var userID = AccountConstant.UserID;
            var date = DateTime.Now;

            var booking = _unitOfWork.Booking
                .Find(m => m.UserID == userID && m.StartDateScheduled <= date && m.EndDateScheduled >= date)
                .OrderByDescending(m => m.ID)
                .FirstOrDefault();

            var driverCar = _unitOfWork.UserCar.FirstOrDefault(m => m.UserID == booking.DriverUserID);
            var location = driverCar.Location.Split(',').ToList();

            var geolocation = new GeolocationViewModel();

            if (location.Count == 2)
            {
                decimal.TryParse(location[0], out var value);
                geolocation.lat = value;

                decimal.TryParse(location[1], out value);
                geolocation.lang = value;
            }

            return Json(new { location });
        }

        #endregion
    }
}

THP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title | THR - Van Rental</title>

    <!--=== Favicon ===-->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />

    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("css", required: false)

    <!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-140396024-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-140396024-1');
    </script>

</head>
<body class="loader-active">

    <!--== Preloader Area Start ==-->
    <div class="preloader">
        <div class="preloader-spinner">
            <div class="loader-content">
                <img src="~/Content/Client/img/preloader.gif" alt="JSOFT">
            </div>
        </div>
    </div>
    <!--== Preloader Area End ==-->

    @Html.Partial("_RootHeader")

    @RenderBody()

    @Html.Partial("_RootFooter")

    <!--== Scroll Top Area Start ==-->
    <div class="scroll-top">
        <img src="~/Content/Client/img/scroll-top2.png" alt="JSOFT">
    </div>
    <!--== Scroll Top Area End ==-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script type="text/javascript">
        $(document).ready(function () {
            $.ajax({
                url: '@Url.Action("HeaderMenu", "Home" )',
                contentType: 'application/json',
                type: 'POST',
                success: function (result) {
                    var html = "";
                    for (var x = 0; x < result.menu.length; x++) {
                        html += '<li><a href="/Home/Topic?url=' + result.menu[x].UrlSlug + '">' + result.menu[x].Name + '</a></li>';
                    }

                    $('#dynamic-pages').append(html);
                },
                error: function () {
                }
            });

            if ($('#notification-list').length > 0) {
                $.ajax({
                    url: '@Url.Action("UserNotification", "Home")',
                    contentType: 'application/json',
                    type: 'POST',
                    success: function (data) {
                        if (data.notifications.length > 0) {
                            for (var x = 0; data.notifications.length > x; x++) {

                                $('#notification-list').append('<li><a href="#">' + data.notifications[x].Message + '</a></li>');
                            }
                        }
                    }
                });
            }
        });
    </script>

    @RenderSection("headerScripts", required: false)
    <script>
        $(document).ready(function () {
            var ErrorMessage = '@TempData["ErrorMessage"]'
            if (ErrorMessage.length > 0) {
                alert(ErrorMessage);
            }
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

THP.Web/Views/Shared/_RootFooter.cshtml
<!--== Footer Area Start ==-->
<section id="footer-area">
    <!-- Footer Widget Start -->
    <div class="footer-widget-area">
        <div class="container">
            <div class="row">
                <!-- Single Footer Widget Start -->
                <div class="col-lg-4 col-md-6">
                    <div class="single-footer-widget">
                        <h2>About Us</h2>
                        <div class="widget-body">
                            <img src="~/Content/Client/img/logo2.png" alt="JSOFT">
                            <p>Lorem ipsum dolored is a sit ameted consectetur adipisicing elit. Nobis magni assumenda distinctio debitis, eum fuga fugiat error reiciendis.</p>

                            <div class="newsletter-area">
                                <form action="index.html">
                                    <input type="email" placeholder="Subscribe Our Newsletter">
                                    <button type="submit" class="newsletter-btn"><i class="fa fa-send"></i></button>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- Single Footer Widget End -->
                <!-- Single Footer Widget Start -->
                <div class="col-lg-4 col-md-6">
                    <div class="single-footer-widget">
                        <h2>Recent Posts</h2>
                        <div class="widget-body">
                            <ul class="recent-post">
                                <li>
                                    <a href="#">
                                        Hello Bangladesh!
                                        <i class="fa fa-long-arrow-right"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Lorem ipsum dolor sit amet
                                        <i class="fa fa-long-arrow-right"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Hello Bangladesh!
                                        <i class="fa fa-long-arrow-right"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        consectetur adipisicing elit?
                                        <i class="fa fa-long-arrow-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Single Footer Widget End -->
                <!-- Single Footer Widget Start -->
                <div class="col-lg-4 col-md-6">
                    <div class="single-footer-widget">
                        <h2>get in touch</h2>
                        <div class="widget-body">
                            <p>Lorem ipsum doloer sited amet, consectetur adipisicing elit. nibh auguea, scelerisque sed</p>

                            <ul class="get-touch">
                                <li><i class="fa fa-map-marker"></i> Ma. Clara, 29 Taytay, Rizal</li>
                                <li><i class="fa fa-mobile"></i> (+63) 917-163-2464</li>
                                <li><i class="fa fa-envelope"></i> thptransportservices@gmail.com</li>
                            </ul>
                            <a href="https://goo.gl/maps/b5mt45MCaPB2" class="map-show" target="_blank">Show Location</a>
                        </div>
                    </div>
                </div>
                <!-- Single Footer Widget End -->
            </div>
        </div>
    </div>
    <!-- Footer Widget End -->
    <!-- Footer Bottom Start -->
    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Bottom End -->
</section>
<!--== Footer Area End ==-->

THP.Web/Views/Shared/_RootHeader.cshtml
@using THP.Web.Models
@using THP.Web.Models.DAL.Data.Enum
<!--== Header Area Start ==-->
<header id="header-area" class="fixed-top">

    <!--== Header Top Start ==-->
    <div id="header-top" class="d-none d-xl-block">
        <div class="container">
            <div class="row">
                <!--== Single HeaderTop Start ==-->
                <div class="col-lg-4 text-left">
                    <i class="fa fa-map-marker"></i> Ma. Clara, 29 Taytay, Rizal
                </div>
                <!--== Single HeaderTop End ==-->
                <!--== Single HeaderTop Start ==-->
                <div class="col-lg-4 text-center">
                    <i class="fa fa-mobile"></i> (+63) 917-163-2464
                </div>
                <!--== Single HeaderTop End ==-->
                <!--== Single HeaderTop Start ==-->
                <div class="col-lg-4 text-right">
                    <i class="fa fa-envelope"></i> thptransportservices@gmail.com
                </div>
                <!--== Single HeaderTop End ==-->
            </div>
        </div>
    </div>
    <!--== Header Top End ==-->
    <!--== Header Bottom Start ==-->
    <div id="header-bottom">
        <div class="container">
            <div class="row">
                <!--== Logo Start ==-->
                <div class="col-lg-4">
                    <a href="@Url.Action("Index", "Home")" class="logo">
                        <img src="~/Content/Client/img/logo2.png" alt="JSOFT">
                    </a>
                </div>
                <!--== Logo End ==-->
                <!--== Main Menu Start ==-->
                <div class="col-lg-8 d-none d-xl-block">
                    <nav class="mainmenu alignright">
                        <ul>
                            <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <!--<li><a href="#">About</a></li>-->
                            <li><a href="@Url.Action("Services", "Home")">Services</a></li>
                            @if (HttpContext.Current.Session["username"] != null)
                            {
                                if (HttpContext.Current.Session["roleID"] != null && HttpContext.Current.Session["roleID"].ToString() != Convert.ToString((int)RoleType.Driver))
                                {
                                    <li>
                                        <a href="#">Book and Track</a>
                                        <ul>
                                            <li><a href="@Url.Action("Index", "Booking")">Rent a Van</a></li>
                                            <li><a href="@Url.Action("Index", "Tracking")">Track</a></li>
                                        </ul>
                                    </li>
                                }
                            }
                            <li>
                                <a href="#">Pages</a>
                                <ul id="dynamic-pages">
                                    <li><a href="@Url.Action("FacebookPage", "Home")">Facebook Page</a></li>
                                </ul>
                            </li>
                            @if (HttpContext.Current.Session["username"] != null)
                            {
                                <li>
                                    <a href="#">Notify</a>
                                    <ul id="notification-list"></ul>
                                </li>
                            }
                            <li>
                                <a href="#">Account</a>
                                @if (HttpContext.Current.Session["username"] != null)
                                {
                                    <ul>
                                        <li><a href="@Url.Action("AccountProfile", "Account")">Profile</a></li>
                                        @if (HttpContext.Current.Session["roleID"] != null
                                        && (HttpContext.Current.Session["roleID"].ToString() == Convert.ToString((int)RoleType.Admin)
                                        || HttpContext.Current.Session["roleID"].ToString() == Convert.ToString((int)RoleType.Driver)))
                                        {
                                            <li><a href="@Url.Action("Index", "Home", new { area = "Admin" })">Administration</a></li>
                                        }
                                        <li><a href="@Url.Action("Logout", "Account")">Log out</a></li>
                                    </ul>
                                }
                                else
                                {
                                    <ul>
                                        <li><a href="@Url.Action("Login", "Account")">Log In</a></li>
                                        <li><a href="@Url.Action("Register", "Account")">Register</a></li>
                                    </ul>
                                }
                            </li>
                        </ul>
                    </nav>
                </div>
                <!--== Main Menu End ==-->
            </div>
        </div>
    </div>
    <!--== Header Bottom End ==-->
</header>
<!--== Header Area End ==-->